name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create executable with Pyinstaller
        run: |
          pyinstaller --onefile --add-data "assets;assets" window.py
        shell: bash
      - name: Upload executable as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: AHKManager
          path: dist/window.exe
